table 'classicmodels products'
	lineageTag: 6939bae4-bb49-40cb-90a1-008f1bdb78f7

	column productCode
		dataType: string
		lineageTag: d44d6693-9314-4c7f-857f-f14cd8b1e995
		summarizeBy: none
		sourceColumn: productCode

		annotation SummarizationSetBy = Automatic

	column productName
		dataType: string
		lineageTag: b341746e-5e6e-42ee-be13-a5541730982e
		summarizeBy: none
		sourceColumn: productName

		annotation SummarizationSetBy = Automatic

	column productScale
		dataType: string
		lineageTag: 9ae87ea2-a695-4873-a081-f171276b3855
		summarizeBy: none
		sourceColumn: productScale

		annotation SummarizationSetBy = Automatic

	column productVendor
		dataType: string
		lineageTag: a10a0a36-fdff-4449-b7f7-29d504187fc2
		summarizeBy: none
		sourceColumn: productVendor

		annotation SummarizationSetBy = Automatic

	column productDescription
		dataType: string
		lineageTag: 7a55b12c-f57c-44a9-85dc-7729fe0ed476
		summarizeBy: none
		sourceColumn: productDescription

		annotation SummarizationSetBy = Automatic

	column quantityInStock
		dataType: int64
		formatString: 0
		lineageTag: 8ae8b115-58eb-4ff3-82cd-8acf4d9b97e7
		summarizeBy: sum
		sourceColumn: quantityInStock

		annotation SummarizationSetBy = Automatic

	column buyPrice
		dataType: double
		lineageTag: f045877c-fd78-4afe-939a-68d53e831cb6
		summarizeBy: sum
		sourceColumn: buyPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MSRP
		dataType: double
		lineageTag: fa6097f7-71cb-46c4-b0c8-885a83b4414d
		summarizeBy: sum
		sourceColumn: MSRP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column productLine
		dataType: string
		lineageTag: 2edf8b60-6564-4246-bb75-c81e11a2a4da
		summarizeBy: none
		sourceColumn: productLine

		annotation SummarizationSetBy = Automatic

	column 'Indirect Cost %' = LOOKUPVALUE('classicmodels productlines'[Indirect Cost],'classicmodels productlines'[productLine],'classicmodels products'[productLine])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: d4a64a19-e9f8-4420-8140-f18af40605b9
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'classicmodels products' = m
		mode: import
		source =
				let
				    Source = MySQL.Database("127.0.0.1:3306", "classicmodels", [ReturnSingleDatabase=true]),
				    classicmodels_products = Source{[Schema="classicmodels",Item="products"]}[Data],
				    #"Removed Blank Rows" = Table.SelectRows(classicmodels_products, each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
				in
				    #"Removed Blank Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

