table 'classicmodels orderdetails'
	lineageTag: 1ebd26b5-acf1-4f48-9b48-8e8ee9d16959

	column orderNumber
		dataType: int64
		formatString: 0
		lineageTag: 9427c8df-0ab3-4b97-bd03-35c98c54709b
		summarizeBy: none
		sourceColumn: orderNumber

		annotation SummarizationSetBy = Automatic

	column productCode
		dataType: string
		lineageTag: 5003b5a4-a4cf-4046-8cfe-99ab088134ef
		summarizeBy: none
		sourceColumn: productCode

		annotation SummarizationSetBy = Automatic

	column quantityOrdered
		dataType: int64
		formatString: 0
		lineageTag: 22b5d88e-f30c-4f23-9e76-0cec2f2acff0
		summarizeBy: sum
		sourceColumn: quantityOrdered

		annotation SummarizationSetBy = Automatic

	column priceEach
		dataType: double
		lineageTag: 0e2118e3-d441-490e-ab27-b3fe079135ee
		summarizeBy: sum
		sourceColumn: priceEach

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column orderLineNumber
		dataType: int64
		formatString: 0
		lineageTag: 27a2bfb6-1058-4557-9f29-3a1b16967e3c
		summarizeBy: sum
		sourceColumn: orderLineNumber

		annotation SummarizationSetBy = Automatic

	column Target = RANDBETWEEN(.5,2)*'classicmodels orderdetails'[quantityOrdered]
		formatString: 0
		lineageTag: 5c36605a-6196-45cc-850a-139b7b07e143
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Inventory Value' = 'classicmodels orderdetails'[quantityOrdered]*'classicmodels orderdetails'[priceEach]
		lineageTag: 94d4955b-df38-4d8e-9345-a4b53d60e6d6
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Full Order Number' = CONCATENATE('classicmodels orderdetails'[orderNumber],'classicmodels orderdetails'[orderLineNumber])
		lineageTag: e7047c00-ea29-45e4-8a54-5c6c49f75aa6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'classicmodels orderdetails' = m
		mode: import
		source =
				let
				    Source = MySQL.Database("127.0.0.1:3306", "classicmodels", [ReturnSingleDatabase=true]),
				    classicmodels_orderdetails = Source{[Schema="classicmodels",Item="orderdetails"]}[Data],
				    #"Removed Blank Rows" = Table.SelectRows(classicmodels_orderdetails, each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
				in
				    #"Removed Blank Rows"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

